# prometheus.yml

global:
  scrape_interval: 15s        # How often to scrape targets
  evaluation_interval: 15s    # How often to evaluate rules (if any)
  # scrape_timeout defaults to 10s

scrape_configs:
  # 1) Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 2) Scrape Node Exporter on the monitored EC2 instance
  - job_name: 'node-exporter-monitored-ec2'
    static_configs:
      - targets:
          - '172.31.33.203:9100'   # e.g. 10.0.1.25:9100
  - job_name: 'node-exporter-prometheus-ec2'
    static_configs:
      - targets:
          - '172.31.35.215:9100'


alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - "/etc/prometheus/rules/*.yml" 
